### ISSUE TITLE
Error on a fresh ubuntu installation

### ISSUE THREAD

**Issue by snorberhuis** [taigaio/taiga-scripts#10]
I tried to use the install scripts on a fresh vm running ubuntu server 14.04 and I tried using docker (guide in #3). 
But both result in a page stating:
"Something happened and our Oompa Loompas are working on it.
Try reloading again soon."

I also tried to look for ways to read any logs that Taiga produces to see what the error is, but I cannot seem to find any. If you could point me in the right direction I could either fix it myself or give a better bug report.

I really want to try Taiga as it seems to fit my needs perfectly. Any help would be appreciated.

**Comment by sairaj3** [comment]
After Successful Taiga Installation admin 123123 is not working. 
Error: Something happened and our Oompa Loompas are working on it.

**Comment by bameda** [comment]
@sairaj3 please write to https://groups.google.com/forum/#!forum/taigaio for setup support and give us more info: what SO?? taiga-back is runing??, logs files, browser console errors,...

**Comment by sthan001** [comment]
Guys not sure if this is solved already.
I ran under this problem and spent 1 day time [1 time investment though].

First is it looks like DNS problem to access taiga hostname from network lan[external to taiga server host/host outside taiga].
Example.
If DNS you picked is registed in network DNS entries then no problem - clients know where to connect for dns hostname [you used on conf files].
If NOT - temporary DNS name used for Taiga server then each clients[outside taiga server - local lan] to be added with hosts entry to know where to connect with front-dist libraries[java script].

Resolution for Non LAN DNS Entry usage for Taiga server:
Add below host entry
192.168.17.39 taiga.tejas.com
Linux: in your /etc/hosts File
Windows: in your C:\Windows\System32\Drivers\etc\hosts or relative file based on OS version

Root cause Seems to Be the logs found in firebug.
[But these problem not occurs immediately takes time by the time you would have completely reinstalled your taiga! I let the browser in firebug mode for more time and captured below exception related to internal dns lookup fails from client browsers.]

Firebug Logs - Captured After say 30 minutes of idle client browser:
Firefox can't establish a connection to the server at ws://taiga.tejas.com/events.
app.js (line 2, col 18537)
WebSocket error: [object Event]
libs.js (line 11)
Firefox can't establish a connection to the server at ws://taiga.tejas.com/events.
app.js (line 2, col 18537)
The connection to ws://taiga.tejas.com/events was interrupted while the page was loading.

Duplicated from https://github.com/taigaio/taiga-front/issues/367
