### ISSUE TITLE
username and password?

### ISSUE THREAD

**Issue by Ryahn** [taigaio/taiga-scripts#24]
I have it up and running but I do not have a username and password to login with. I used the setup-server.sh on ubuntu 14.04

Here is the install log https://pastebin.com/kp5QZ5Gt

**Comment by superalex** [comment]
The default username and password taiga creates is admin with password 123123, isn't it working?

**Comment by Ryahn** [comment]
No, says its incorrect

**Comment by superalex** [comment]
Checking your logs it seems that an installation failed could you execute 
```
workon taiga
pip install -r requirements.txt
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py loaddata initial_role
python manage.py collectstatic --noinput
```

from taiga-back and check if it's still happening?

**Comment by Ryahn** [comment]
Got an error and red text after running pip install -r requirements.txt

http://paste.ubuntu.com/10514817/

**Comment by superalex** [comment]
Some people have that kind of problem with pip when they have systems with small RAM, if it's a virtual machine, could you increase it?

**Comment by Ryahn** [comment]
I would have to reinstall everything on the box. I can only go up but not down. What are the system requirements to running taiga?

**Comment by superalex** [comment]
According to this http://stackoverflow.com/questions/16149613/installing-lxml-with-pip-in-virtualenv-ubuntu-12-10-error-command-gcc-failed?lq=1 and this http://stackoverflow.com/questions/19894197/cant-installing-lxml-on-ubuntu-12-04 it depends on the free RAM you have. You can also create a swap file for the installing workaround so you won't have to reinstall everything.

**Comment by Ryahn** [comment]
I will get back to you on this after I get the swap up

**Comment by superalex** [comment]
Great! :+1:

**Comment by Ryahn** [comment]
python manage.py migrate --noinput

Got this after the above command https://pastebin.com/6C74G6u5

**Comment by superalex** [comment]
pip install -r requirements.txt install the celery package, this package installs kombu:

```
pip show celery
---
Name: celery
Version: 3.1.17
Location: /home/superalex/Envs/taiga/lib/python3.4/site-packages
Requires: pytz, kombu, billiard
```

It seems your pip install didn't work correctly, could try to reinstall celery package?

```
pip install celery
```

**Comment by Ryahn** [comment]
I was able to get it installed. The VPS I had it on, was just too small.

**Comment by Ryahn** [comment]
The VPS was too small that I was using

**Comment by bameda** [comment]
Great :dancers: :dancers: 

Enjoy Taiga.

**Comment by Ryahn** [comment]
VPS needs at least 1GB RAM and 1GB Swap or larger

**Comment by luminousmg** [comment]
Hello, I am still having trouble logging into Taiga on my Ubuntu 14.04 VPS with 2GB of ram.  I closely followed the instructions on http://taigaio.github.io/taiga-doc/dist/setup-production.html

The log-in screen loads, but when I enter the default user admin and password 123123, I get an error page.

I looked into the postgresql database and found that the tables have been populated and the user admin exists within the users_user table.  I noticed that the users_role is empty though.

Is there anything that I could be missing?  I went through all of the logs in ~logs/ and found no error messages.

Thanks!  I'm really looking forward to using this software

**Comment by bameda** [comment]
Can you see the browser console to show the request sent to the api?

**Comment by luminousmg** [comment]
Ah ha...  Thanks for the tip!  The following error appeared in the console: 

OPTIONS http://myserver:8000/api/v1/auth net::ERR_ADDRESS_UNREACHABLE

It looks like the backend server is not running or is not accessible.  I'm wondering if I should try to re-install.  

I tried to manually start the  the server
workon taiga 
python manage.py runserver

it clears all system checks.  Starts development server at 127.0.0.1:8000

I'm wondering if it is not working because it is launching at local 127.0.0.1?

**Comment by luminousmg** [comment]
Hello, I found the following thread that pointed me in the right direction:

https://github.com/taigaio/taiga-scripts/issues/10

I removed the taiga-back and taiga-front directories and downloaded taiga-scripts.

Ran setup-server.sh and everything went well from there.  I'm able to log-in and use the system.

Thanks again!  This software is amazing!  Great job!

**Comment by bameda** [comment]
Great \o/ :dancers:

**Comment by caghan** [comment]
I had the similar issue after I followed "Taiga: Setup production environment". I fixed "OPTIONS http://myserver:8000/api/v1/auth net::ERR_ADDRESS_UNREACHABLE" issue as follows:

* Check taiga-back/settings/local.py and changed below URLs:
    * http://myserver:8000/media/ -> http://myserver/media/
    * http://myserver:8000/static/  -> http://myserver/static/

* Check taiga-front-dist/dist/conf.json and changed below URLs:
    * "api": "http://myserver:8000/api/v1/",              ->    "api": "http://myserver/api/v1/",
    * "eventsUrl": "ws://myserver:8000/events",     ->    "eventsUrl": "ws://myserver/events",
* Reload circus and nginx:
    * $ sudo service circus restart
    * $ sudo service nginx restart
* Worked like a charm. Now I can login with default admin credentials. 

IMHO, adding above steps to https://taigaio.github.io/taiga-doc/dist/setup-production.html could be helpful for those like me forgetting to change config files for the taiga-back ports after nginx installation/setup.

BTW, thanks for the great work Taiga.io team!

**Comment by superalex** [comment]
Hello @caghan, thank you very much for your comments!

I've checked https://taigaio.github.io/taiga-doc/dist/setup-production.html and can't find references to http://myserver:8000/media/  http://myserver:8000/static/ http://myserver:8000/api/v1/ or ws://myserver:8000/events

Pull request to taiga-doc repo are of course welcome if you find any errors on it :)

Regards!,

**Comment by caghan** [comment]
Hi @superalex, sorry for the miss explanation at my previous post. 

@ "3.4. Verification" section of the setup-production, the verification URL by nature is http://localhost:8000/api/v1/ (because of running server command: "python manage.py runserver"). Thus, I put  <myserverIP>:8000 for the configurations of both taiga-back and taiga-front-dist. But after applying the final step of the document(install/configuring nginx), I forgot to change them into <myserverIP>:80.  

I'll tried to add this to taiga-doc as soon as possible.

Many thanks!

**Comment by superalex** [comment]
Thanks @caghan but the "python manage.py runserver" in that part of the doc was just trying to check that django can boot correctly that's why we don't use :8000 on the rest of the doc.

Regards!,

**Comment by jtfogarty** [comment]
Hi @superalex, I'm attempting to run the Docker container, benhutchins/taiga on [Mantl](www.mantl.io)  I have it running but am not able to login.  Interestingly, I am able to login to server:8000/api/v1/#
When I connect to the database, I see 57 tables in the Taiga database and see an admin entry in users_user.  Any ideas on is?  Thanks

**Comment by superalex** [comment]
Hello @jtfogarty could you check the API url set in your http://taiga_access_url/conf.json file is accessible from your browser?

**Comment by jtfogarty** [comment]
@superalex, that was the problem.  I had TAIGA_HOSTNAME set to taiga-front.service.consul which is how Mantl configures the network.  Thanks for the fast reply!!!

**Comment by superalex** [comment]
You are welcome @jtfogarty ;)

**Comment by cyberfarer** [comment]
Greetings, if anyone is following this how-to, http://taigaio.github.io/taiga-doc/dist/setup-production.html, be aware there appears to be an error in the nginx conf file. The conf file shows: proxy_pass http://127.0.0.1:8001/api; 

But on my system, following the instructions, the port was on 8000.

**Comment by superalex** [comment]
@cyberfarer if following those instructions nothing should be served in 8000, just the 3.4 verification step will use that port but if you stop the runserver command nothing will be listening on that port.

In the "Initial configuration for circus on ~/conf/circus.ini" section port 8001 is configured to serve taiga-back.

Regards!,

**Comment by myktux** [comment]
I had the same admin login problem because Ubuntu 16.04 LTS uses _systemd_ instead of _upstartd_ and the instructions for setting up CIRCUS at the end of "6. FINAL STEPS" [http://taigaio.github.io/taiga-doc/dist/setup-production.html#circus-and-gunicorn](url) fails on this version of Ubuntu.

To properly configure Circus with _systemd_ I followed ssplatt instructions here [https://gist.github.com/ssplatt/522144c56dc6bb93e9f7](url). But PIP2 installs _circusd_ at _/user/local/bin/circusd_ and Circus config file in the tutorial is saved at _/home/taiga/conf/circus.ini

So the right _circus.service_ file in _/lib/systemd/system_ file should be:

`[Unit]`
`Description=Circus for Taiga`
`After=syslog.target`
`After=network.target`

`[Service]`
`Type=simple`
`User=taiga`
`Group=taiga`
**`ExecStart=/usr/local/bin/circusd /home/taiga/conf/circus.ini`**

`# Give a reasonable amount of time for the server to start up/shut down`
`TimeoutSec=300`

`[Install]`
`WantedBy=multi-user.target`

Also, the tut forgets to mention the installation command for **gunicorn** using PIP. So, after the installation of Circus, do this:

`sudo pip2 install gunicorn`

Then, check if circus is working:

`sudo systemctl status circus`

**Comment by myktux** [comment]
To make circus start with your system boot, issue this on your command line:
`sudo systemctl enable circus`

**Comment by bameda** [comment]
This branch of taiga-scripts works in ubuntu 16.04

https://github.com/taigaio/taiga-scripts/tree/ubuntu-16.04

it will be released with the next version of Taiga but you can use it now.
