### ISSUE TITLE
Make an Ansible playbook

### ISSUE THREAD

**Issue by ayr-ton** [taigaio/taiga-scripts#32]
For orchestrate the deploy, make an ansible playbook.

**Comment by ayr-ton** [comment]
I could make a pull request if you guys like this feature.

**Comment by superalex** [comment]
Hello @ayr-ton ,

You could create a new github project for it and it could appear in our doc (section "other ways to setup initial environment") -> http://taigaio.github.io/taiga-doc/dist/setup-alternatives.html

Regards!,

**Comment by superalex** [comment]
Hello @ayr-ton 

I just remembered there is an ansible taiga project here -> https://github.com/JScott/ansible-taiga

Regards!

**Comment by ayr-ton** [comment]
Thank you!

**Comment by superalex** [comment]
You are welcome ;)

**Comment by seagoj** [comment]
Although [ansible-taiga](https://github.com/JScott/ansible-taiga) does get the job done, it would be nice if there was an ansible playbook that utilized the latest version of this build script. That way the playbook isn't always lagging being the build requirements.

I'm trying to accomplish something like that, but I'm struggling with making the virtualenvs work from the ansible script. For example when I run setup-server.sh, ansible just never returns. I suspect that's because the virtualenv never closes.

**Comment by jpgrace** [comment]
It should be noted that the linked github repo ([https://github.com/JScott/ansible-taiga](https://github.com/JScott/ansible-taiga)) no longer builds, because there are dependencies that are 404.

**Comment by ayr-ton** [comment]
@jpgrace Need to debug to see what is happening
@jscott Is it no longer being maintained?

**Comment by lifenautjoe** [comment]
any plans for this?
