### ISSUE TITLE
User Pass for PostgreSQL DB

### ISSUE THREAD

**Issue by bagas9425** [taigaio/taiga-scripts#52]
Hi, all.
What are Default user and pass for PostgreSQL DB using Taiga Sctipts?
I've tried user postgres pass postgres but got failed.

I want to integrate Taiga with Metabase.

**Comment by superalex** [comment]
By default there is no user/password for postgresql because of the Trust authentication method (https://www.postgresql.org/docs/9.1/static/auth-methods.html), if you are the user taiga in the system then you can connect to the Taiga database. You could update your postgresql settings to make the database work with another authentication method.

Regards,

**Comment by ston3o** [comment]
I have this use case too, here what I do:

```bash
# Allow remote connection   
echo "listen_addresses = '*'" >> /etc/postgresql/9.5/main/postgresql.conf
cat >> /etc/postgresql/9.5/main/pg_hba.conf << EOF      
host    all             all              0.0.0.0/0                   md5
host    all             all              ::/0                        md5
EOF                         

# Add metabase user
psql -c "CREATE USER metabase WITH PASSWORD 'password';"

# Grant user permissions
psql -c "GRANT ALL PRIVILEGES ON database taiga to metabase;"
```
